In [1]:
import pandas as pd
import ast
import numpy as np
import matplotlib.pyplot as plt

In [2]:
path = "./datasets/dataV.6.csv"
df = pd.read_csv(path)

In [6]:
one_day_df = df[:148]

# Get unique values for CountryName, Region, and Continent
unique_countries = one_day_df['CountryName']

In [43]:
print(unique_countries)
print(unique_countries.shape)

0           Mali
1         Greece
2        Hungary
3         Bhutan
4         Guyana
         ...    
143     Bulgaria
144      Belarus
145        China
146    Guatemala
147    Venezuela
Name: CountryName, Length: 148, dtype: object
(148,)


In [42]:
adjacency_file = "adjacency.txt"
txt = ''
with open(adjacency_file, 'r') as file:
    for line in file:
        txt += line.strip()
        
print(txt[17:]) 

{"Abyei" : ["South Sudan","Sudan"],"Afghanistan" : ["Iran (Islamic Republic of)", "Turkmenistan","Uzbekistan","Tajikistan","China","Pakistan"],"Albania" : ["Greece","The former Yugoslav Republic of Macedonia","Montenegro"],"Algeria" : ["Morocco","Tunisia","Niger","Mali"],"Angola" : ["Namibia","Zambia","Democratic Republic of the Congo"],"Argentina" : ["Uruguay","Brazil","Paraguay","Bolivia","Chile"],"Armenia" : ["Georgia","Iran (Islamic Republic of)","Azerbaijan", "Turkey"],"Arunachal Pradesh" : ["India","Bhutan","China","Myanmar"],"Australia" : [],"Azerbaijan" : ["Russian Federation","Georgia","Armenia","Iran (Islamic Republic of)"],"Bahamas" : [],"Bangladesh" : ["India","Myanmar"],"Belarus" : ["Lithuania","Latvia","Russian Federation","Ukraine","Poland"],"Belize" : ["Guatemala","Mexico"],"Benin" : ["Togo","Burkina Faso","Niger","Nigeria"],"Bhutan" : ["India","Arunachal Pradesh","China"],"Bolivia" : ["Brazil","Paraguay","Argentina","Chile","Peru"],"Bosnia & Herzegovina" : ["Croatia","

In [41]:
adjacency_dict = ast.literal_eval(txt[17:])
print(type(adjacency_dict))

<class 'dict'>


In [47]:
adjacency_matrix = np.zeros((len(unique_countries), len(unique_countries)), dtype=int)

# Iterate over unique countries
for i, country in enumerate(unique_countries):
    # Check if the country is in the adjacency dictionary
    if country in adjacency_dict:
        # Iterate over its adjacency list
        for neighbor in adjacency_dict[country]:
            # Find the index of the neighbor in the unique_countries array
            j = np.where(unique_countries == neighbor)[0]
            # If the neighbor is found, mark the corresponding entry in the adjacency matrix
            if len(j) > 0:
                adjacency_matrix[i, j] = 1

# Print the adjacency matrix
print(adjacency_matrix[2])

[0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [49]:
import csv

# Define the file name
csv_filename = "./datasets/adjacency_matrix.csv"

# Write the adjacency matrix to a CSV file
with open(csv_filename, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    # Write the header row with country names
    writer.writerow(unique_countries)
    # Write the adjacency matrix
    writer.writerows(adjacency_matrix)


In [54]:
n = len(unique_countries)
#symetric matric
adjacency_matrix_sym = np.zeros((n, n), dtype=int)

for i in range(n):
    for j in range(n):
        if(adjacency_matrix[i,j] or adjacency_matrix[j,i]):
            adjacency_matrix_sym[i,j] = 1
        else:
            adjacency_matrix_sym[i,j] = 0
print(adjacency_matrix_sym)
print(adjacency_matrix.sum())
print(adjacency_matrix_sym.sum())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
263
510


In [55]:
import csv

# Define the file name
csv_filename = "./datasets/adjacency_matrix_sym.csv"

# Write the adjacency matrix to a CSV file
with open(csv_filename, 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    # Write the header row with country names
    writer.writerow(unique_countries)
    # Write the adjacency matrix
    writer.writerows(adjacency_matrix_sym)